### ISSUE TITLE
iOS app is crashing due to NSInvalidArgumentException in deploy plugin

### ISSUE THREAD

**Issue by viveksinha121** [ionic-team/ionic-plugin-deploy#135]
I have integrated deploy in my ionic 3 app. It is working fine in android but in iOS it sometimes crashes with following error logs recorded at crashlytics:
![screen shot 2017-08-11 at 5 22 36 pm](https://user-images.githubusercontent.com/11805204/29238511-bee682ac-7f54-11e7-88fe-0476b0eb52a6.png)

**Comment by viveksinha121** [comment]
Can anyone help? There are more than 1200 crashes due to this issue in last one month.

**Comment by NickMele** [comment]
I am having this same exact problem and I cannot find a solution to prevent the crash. Seems like the best course of action is to get your users to update to a version that has resolved this crash.

**Comment by media4learning** [comment]
They tried to fix this in the latest version of cordova-plugin-ionic. However now the plugin has even more problems. I would avoid using the pro backend for a few months until they can get it working properly. I have been trying to get a simple deploy working for weeks now and it's just a nightmare.

**Comment by NickMele** [comment]
This whole platform has been a nightmare

**Comment by deliverymanager** [comment]
I am a little bit confused.
It says in the description that this plugin is not for the PRO version.
Are you using the PRO backend or the LEGACY?

**Comment by media4learning** [comment]
Hmm this issue has been fixed in cordova-plugin-ionic - for the pro dashboard. I think viveksinha121 has put this in the wrong repo.

**Comment by viveksinha121** [comment]
The problem was not with ionic. Actual problem was my old native app in which I was using uuid as a key for one NSUserDefaults. Then I moved to ionic & integrated ionic deploy plugin which is also using uuid for one NSUserDefaults. So when user upgrades from their native app to hybrid app, this uuid key created problem. I had to communicate this earlier. My bad.

**Comment by mlynch** [comment]
Hi all,

It seems there's some conflicting information on the issue here. For those still seeing it beyond what @viveksinha121 reported, can you provide more information on the stacktrace or error you're seeing?
